openapi: 3.0.1
info:
  title: Protoss Part Search API
  version: 1.0.0
  description: 一系列用于芯灵前端与后端交互的API。此文档中所列API不会开放给普通用户
servers:
  - url: http://192.168.50.100:5010
tags:
  - name: BOM
  - name: Search
  - name: Analyze
paths:
  /cut:
    get:
      summary: 对搜索语句进行分词
      tags:
        - Analyze
      parameters:
        - in: query
          name: q
          schema:
            type: string
          example: CAP CER 4.7UF 25V X5R 0603
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    type: string
                example:
                  - - CAP
                    - CER
                    - 4.7UF
                    - 25V
                    - X5R
                    - '0603'
  
  /check_keywords:
    post:
      summary: 检查一条字符串是否可能为合法的MPN
      description: ""
      tags:
        - Analyze
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: 
                type: string
            example: ["4k7", "7D471K"]
        required: True
      responses:
        '200':
          description: Successful operation
          content:
              application/json:
                schema:
                  type: array
                  items:
                    type: boolean
                example: [false, true]
  
  
  /analyze:
    post:
      summary: 对单条material进行分析
      description: ''
      operationId: ''
      tags:
        - Analyze
      requestBody:
        description: Update an existent pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Material'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Signal'
              example:
                - endpoint: mpn
                  unit: null
                  value: CC0402KRX7R7BB104
                - endpoint: category
                  unit: null
                  value: Capacitors
                - endpoint: numeric_keyword
                  unit: null
                  value: '0402'
                - endpoint: category
                  unit: null
                  value: Capacitors
                - endpoint: numeric_keyword
                  unit: volt
                  value: '16'
                - endpoint: category
                  unit: null
                  value: Ceramic Capacitors
                - endpoint: numeric_keyword
                  unit: micro-farad
                  value: '0.1'
                - endpoint: attr.temperature_characteristic
                  unit: null
                  value: X7R
                - endpoint: package
                  unit: null
                  value: '0402'
                - endpoint: org_text
                  unit: null
                  value: CAP CER 0.1UF 16V X7R 0402
  /bom_components_match:
    post:
      summary: 为BOM中的物料匹配器件
      description: ''
      operationId: ''
      tags:
        - BOM
      requestBody:
        description: Update an existent pet in the store
        content:
          application/json:
            schema:
              type: array
              items:
                allOf:
                  - $ref: '#/components/schemas/Material'
                  - type: object
                    properties:
                      signals:
                        description: 如果提供，则使用传入的信号进行匹配
                        type: array
                        items:
                          $ref: '#/components/schemas/Signal'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BOMMatchResult'
  /get_supplier_parts_component_id_batch:
    post:
      tags:
        - Search
      summary: 根据id列表批量查询供应链信息
      requestBody:
        description: component id列表
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
              example:
                - 1
                - 2
                - 3
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplierParts'
  /get_supplier_parts_component_id/{component_id}:
    get:
      tags:
        - Search
      summary: 根据id查询供应链信息
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplierParts'
      parameters:
        - name: component_id
          in: path
          description: phyical part id
          required: true
          schema:
            type: integer
  /search_component_by_desc:
    get:
      tags:
        - Search
      summary: 按照描述查找器件
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ComponentSearchResultCollection'
      parameters:
        - in: query
          name: q
          schema:
            type: string
        - in: query
          name: highlight
          description: 返回高亮匹配
          schema:
            type: boolean
        - in: query
          name: aggCnt
          description: 是否返回聚合计数
          schema:
            type: boolean
    post:
      tags:
        - Search
      summary: 按照描述与条件查找器件
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ComponentSearchResultCollection'
      requestBody:
        description: 描述与条件
        content:
          application/json:
            schema:
              type: object
              properties:
                aggregations:
                  type: boolean
                  description: 是否返回切片
                highlights:
                  type: boolean
                source:
                  type: boolean
                  description: 返回数据中是否需要包含器件数据，与aggregations不能同时为False
                query:
                  type: string
                  example: 贴片电感，0201
                signals:
                  type: array
                  items:
                    $ref: '#/components/schemas/Signal'
                  description: 通过分析query得到的信号，如提供，则强制使用传入的信号进行搜索
                size:
                  type: integer
                  example: 20
                from:
                  type: integer
                  example: 0
                parameters:
                  type: object
                  description: 查询条件，条件之间为“与”关系
                  properties:
                    mpn:
                      type: array
                      items:
                        type: string
                        example: BLM03HG102SN1D
                    manufacturer:
                      type: array
                      items:
                        type: string
                        example: Murata
                    manufacturer_id:
                      type: array
                      items:
                        type: integer
                        example: 5139
                    category:
                      type: array
                      items:
                        type: string
                        example: Ferrite Beads and Chips
                    category_id:
                      type: array
                      items:
                        type: integer
                        example: 161
                    package:
                      type: array
                      items:
                        type: string
                        example: 201
                    specs:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            example: Current Rating
                          values:
                            type: array
                            items:
                              type: string
                              example: 125 mA
        required: true
  /get_component_by_component_id/{component_id}:
    get:
      tags:
        - Search
      summary: 根据id查询器件信息
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Part'
      parameters:
        - name: component_id
          in: path
          description: phyical part id
          required: true
          schema:
            type: integer
  /get_component_details_by_component_id/{component_id}:
    get:
      tags:
        - Search
      summary: 根据id查询器件详细信息，包括文档，模型和参数
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PartDetail'
      parameters:
        - name: component_id
          in: path
          description: phyical part id
          required: true
          schema:
            type: integer
            
            
  /search_component_aggregation:
    post:
      tags:
        - Search
      summary: 返回搜索结果的聚合切片
      requestBody:
        description: 描述与条件
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  example: 贴片电感，0201
                signals:
                  type: array
                  items:
                    $ref: '#/components/schemas/Signal'
                  description: 通过分析query得到的信号，如提供，则强制使用传入的信号进行搜索
                parameters:
                  type: object
                  description: 查询条件，条件之间为“与”关系
                  properties:
                    mpn:
                      type: array
                      items:
                        type: string
                        example: BLM03HG102SN1D
                    manufacturer:
                      type: array
                      items:
                        type: string
                        example: Murata
                    manufacturer_id:
                      type: array
                      items:
                        type: integer
                        example: 5139
                    category:
                      type: array
                      items:
                        type: string
                        example: Ferrite Beads and Chips
                    category_id:
                      type: array
                      items:
                        type: integer
                        example: 161
                    package:
                      type: array
                      items:
                        type: string
                        example: 201
                    specs:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            example: Current Rating
                          values:
                            type: array
                            items:
                              type: string
                              example: 125 mA
                param_aggs:
                  description: 指定要返回的属性聚合，如果不提供，则接口不返回任何与属性相关的聚合
                  type: array
                  items:
                    type: string
                  example: ["Capacitance", "Series"]
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bucket'
      
    
components:
  schemas:
    Material:
      type: object
      properties:
        line_no:
          type: string
          description: 物料在BOM中的位置
          example: 10
        mpn:
          type: string
          example: DSS24
        manufacturer:
          type: string
          example: Yageo
        package:
          type: string
          example: SOT-22
        reference:
          type: string
          example: C1, C2
        quantity:
          type: integer
        sku:
          type: string
          example: 1N5819FSTR-ND
        comment:
          type: string
          example: 2.2uH 4.3A
    Specs:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
            example: Current
          value:
            type: string
            example: 1.0 ampere
          value_display:
            type: string
            example: 1 A
    TechDocs:
      type: array
      items:
        type: object
        properties:
          url:
            type: string
            example: //protoss_docs/declecu125.pdf
          title:
            type: string
            example: Accelerometer, Gyroscope, 6 Axis Sensor Output
          doc_type:
            type: string
            enum:
              - datasheet
              - tech drawing
              - pcn
              - compliance
    EdaModels:
      type: array
      items:
        type: object
        properties:
          uri:
            type: string
          name:
            type: string
          typ:
            type: string
            enum:
              - 3d
              - eda
              - simulation
          sub_typ:
            type: string
            enum:
              - step
              - igs_iges
              - sehematic
              - pcb
              - complied library
              - bsdl
              - ibis
              - thermal model
              - simplis
              - s_parameterds
              - spice
          supported:
            type: string
            enum:
              - altium designer
              - eagle
              - pads_xpedition
              - orcad_allegro
              - easyeda
              - kicad
    SupplierParts:
      type: array
      items:
        type: object
        properties:
          component_id:
            type: integer
          sku:
            type: string
            example: ICM-42688-P
          moq:
            type: integer
            example: 1000
          packaging:
            type: string
            example: Tape and Reel
          factory_lead_days:
            type: integer
            example: 30
          distributor:
            type: string
            example: Digikey
          distributor_url:
            type: string
            example: >-
              https://www.digikey.com/en/products/detail/phoenix-contact/1751248/2511016
          prices:
            type: array
            items:
              type: object
              properties:
                currency:
                  type: string
                  example: usd
                price:
                  type: number
                  example: 15
          price_break:
            type: array
            items:
              type: integer
          stock:
            type: integer
            example: 15989
    Part:
      type: object
      properties:
        component_id:
          description: leader part id
          type: integer
          example: 2958605
        mpn:
          type: string
          example: MURRPE5C1H102J2K!A
        manufacturer:
          type: string
          example: Murata
        category:
          type: string
          example: PTC Resettable Fuses
        category_id:
          type: integer
          example: 396
        package:
          type: string
          example: SOD323
        part_desc:
          description: component description
          type: string
        image:
          type: string
          description: component image uri
        datasheet:
          type: string
    PartDetail:
      allOf:
        - $ref: '#/components/schemas/Part'
        - type: object
          properties:
            specs:
              $ref: '#/components/schemas/Specs'
            tech_docs:
              $ref: '#/components/schemas/TechDocs'
            models:
              $ref: '#/components/schemas/EdaModels'
    ComponentSearchResult:
      type: array
      items:
        allOf:
          - $ref: '#/components/schemas/Part'
          - type: object
            properties:
              highlights:
                description: 搜索命中的字段，可用于计算置信度
                type: array
                items:
                  type: object
                  properties:
                    filed:
                      type: string
                      enum:
                        - spec
                        - key_spec
                        - mpn
                        - mpn_normalized
                        - category
                        - manufacturer
                        - package
                    value:
                      type: string
    Bucket:
      type: object
      properties:
        name:
          type: string
        count:
          type: integer
        buckets:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/Bucket'
      example: '{name: specs, count: 1257, buckets:[{name: temp, count: 543}]}'
    ComponentSearchResultCollection:
      type: object
      properties:
        hits:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/ComponentSearchResult'
        keywords:
          description: 搜索程序分析comment得到的搜索关键词
          type: array
          items:
            type: string
          example:
            - connector
            - pins:2
            - green
        aggregation:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/Bucket'
    BOMMatchResult:
      type: array
      items:
        type: object
        properties:
          source:
            $ref: '#/components/schemas/Material'
          parts:
            $ref: '#/components/schemas/ComponentSearchResult'
    Signal:
      type: object
      properties:
        endpoint:
          type: string
        unit:
          type: string
        value:
          type: string
      example:
        endpoint: numeric_keyword
        unit: micro-farad
        value: '0.1'
